"""
step3_sensitivity_scan.py
-------------------------
Purpose: Run the single-layer quantization experiment for every Linear
layer in DistilBERT automatically. This is step2's core loop, scaled to
all 52 layers. The output is the raw data that step4 plots as a chart.

Runtime : ~35-40 minutes on CPU.
          Start this and step away. Do not interrupt it.

Resume  : Results are saved to sensitivity_results.json after EACH layer.
          If the script crashes, re-run it — already-completed layers are
          skipped automatically. Delete the JSON to restart from scratch.

Outputs :
  sensitivity_results.json  ← machine-readable, read by step4
  sensitivity_summary.txt   ← human-readable ranked list

Requires: layer_names.txt generated by step1_explore_model.py
"""

import torch
import copy
import json
import os
import time
import torch.nn as nn
import torch.nn.functional as F
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from datasets import load_dataset

# ── Configuration ──────────────────────────────────────────────────────────────
MODEL_NAME   = "distilbert-base-uncased-finetuned-sst-2-english"
EVAL_SAMPLES = 400      # 400 gives a reliable signal without taking too long
BATCH_SIZE   = 16
RESULTS_FILE = "sensitivity_results.json"
LAYER_FILE   = "layer_names.txt"

# KL threshold that divides SENSITIVE vs RESILIENT.
# Calibrated on DistilBERT SST-2 — adjust after seeing your results.
KL_THRESHOLD = 1e-4


# ── Core Functions (same logic as step2, kept here for self-containment) ───────

def get_parent_and_child(model: nn.Module, layer_name: str):
    parts  = layer_name.split('.')
    parent = model
    for part in parts[:-1]:
        parent = getattr(parent, part)
    return parent, parts[-1]


def quantize_one_layer(model: nn.Module, layer_name: str) -> nn.Module:
    """Deep-copies the model and quantizes only the named layer to INT8."""
    model_copy               = copy.deepcopy(model)
    parent, child_name       = get_parent_and_child(model_copy, layer_name)
    original_layer           = getattr(parent, child_name)
    wrapper                  = nn.Sequential(original_layer)
    quantized_wrapper        = torch.quantization.quantize_dynamic(
                                   wrapper, {nn.Linear}, dtype=torch.qint8)
    setattr(parent, child_name, quantized_wrapper[0])
    return model_copy


def get_all_logits(model: nn.Module, tokenizer, texts: list) -> torch.Tensor:
    """Runs inference on all texts. Returns [N, num_classes] logit tensor."""
    model.eval()
    all_logits = []
    with torch.no_grad():
        for start in range(0, len(texts), BATCH_SIZE):
            batch  = texts[start : start + BATCH_SIZE]
            inputs = tokenizer(batch, padding=True, truncation=True,
                               max_length=128, return_tensors="pt")
            all_logits.append(model(**inputs).logits)
    return torch.cat(all_logits, dim=0)


def compute_kl(logits_orig: torch.Tensor, logits_quant: torch.Tensor) -> float:
    """
    Mean KL divergence between original and quantized softmax distributions.
    KL(P || Q) where P = softmax(original), Q = softmax(quantized).
    Higher = quantizing this layer disturbed the model more = more sensitive.
    """
    P = F.softmax(logits_orig,  dim=-1)
    Q = F.softmax(logits_quant, dim=-1)
    return F.kl_div(Q.log(), P, reduction='batchmean').item()


def compute_mse(logits_orig: torch.Tensor, logits_quant: torch.Tensor) -> float:
    """Mean squared error between original and quantized logits."""
    return F.mse_loss(logits_quant, logits_orig).item()


def compute_accuracy(logits: torch.Tensor, labels: list) -> float:
    preds   = torch.argmax(logits, dim=-1).tolist()
    correct = sum(p == l for p, l in zip(preds, labels))
    return correct / len(labels)


# ── Checkpoint Helpers ─────────────────────────────────────────────────────────

def load_results() -> dict:
    """Load existing results from disk if available (for resume support)."""
    if os.path.exists(RESULTS_FILE):
        with open(RESULTS_FILE, 'r') as f:
            return json.load(f)
    return {}


def save_results(results: dict):
    """Persist current results to disk immediately after each layer."""
    with open(RESULTS_FILE, 'w') as f:
        json.dump(results, f, indent=2)


# ── Progress Helpers ───────────────────────────────────────────────────────────

def format_eta(seconds: float) -> str:
    if seconds < 60:
        return f"{seconds:.0f}s"
    return f"{seconds/60:.1f}m"


def print_row(idx, name, kl, mse, verdict, suffix=""):
    col = 56
    print(f"  {idx:<4} {name:<{col}} {kl:<12.6f} {mse:<12.6f} {verdict}{suffix}")


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    print("=" * 80)
    print("  STEP 3: Full Sensitivity Scan — All Layers")
    print("=" * 80)

    # ── Load layer list from step1 ─────────────────────────────────────────────
    if not os.path.exists(LAYER_FILE):
        print(f"\n  ERROR: {LAYER_FILE} not found.")
        print(f"  Run step1_explore_model.py first to generate it.")
        return

    with open(LAYER_FILE, 'r') as f:
        layer_names = [line.strip() for line in f if line.strip()]

    # ── Resume check ──────────────────────────────────────────────────────────
    results   = load_results()
    completed = set(results.keys())
    remaining = [l for l in layer_names if l not in completed]

    print(f"\n  Total layers   : {len(layer_names)}")
    print(f"  Already done   : {len(completed)}")
    print(f"  To run now     : {len(remaining)}")
    print(f"  Eval samples   : {EVAL_SAMPLES}")

    if len(remaining) == 0:
        print("\n  All layers already scanned. Delete sensitivity_results.json to re-run.")
        return

    # ── Load model, tokenizer, dataset ────────────────────────────────────────
    print("\n  Loading model and tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model     = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME)
    model.eval()

    print(f"  Loading {EVAL_SAMPLES} SST-2 validation samples...")
    dataset = load_dataset("glue", "sst2", split=f"validation[:{EVAL_SAMPLES}]")
    texts   = dataset["sentence"]
    labels  = dataset["label"]

    # ── Baseline FP32 logits — computed ONCE, reused across all 52 layers ─────
    # This saves significant time: we don't re-run the full FP32 model 52 times.
    print("\n  Collecting FP32 baseline logits (once, reused for every layer)...")
    logits_fp32 = get_all_logits(model, tokenizer, texts)
    acc_fp32    = compute_accuracy(logits_fp32, labels)
    print(f"  Baseline FP32 accuracy: {acc_fp32 * 100:.2f}%\n")

    # ── Table header ──────────────────────────────────────────────────────────
    col = 56
    header = f"  {'#':<4} {'Layer Name':<{col}} {'KL Score':<12} {'MSE':<12} Verdict"
    print(header)
    print("  " + "─" * (len(header) - 2))

    # Print cached layers first so table is complete
    for i, name in enumerate(layer_names):
        if name in completed:
            r       = results[name]
            verdict = "SENSITIVE" if r['kl_divergence'] > KL_THRESHOLD else "RESILIENT"
            print_row(i, name, r['kl_divergence'], r['mse'], verdict, "  [cached]")

    # ── Main scan loop ─────────────────────────────────────────────────────────
    scan_start     = time.time()
    layers_run     = 0

    for i, layer_name in enumerate(layer_names):
        if layer_name in completed:
            continue

        layer_start = time.time()

        # The core experiment: quantize this layer only, measure distribution shift
        q_model      = quantize_one_layer(model, layer_name)
        logits_quant = get_all_logits(q_model, tokenizer, texts)

        kl_score  = compute_kl(logits_fp32,  logits_quant)
        mse_score = compute_mse(logits_fp32, logits_quant)
        acc_quant = compute_accuracy(logits_quant, labels)
        acc_drop  = (acc_fp32 - acc_quant) * 100
        layer_sec = time.time() - layer_start

        # Persist immediately — never lose a completed layer
        results[layer_name] = {
            "layer_index"   : i,
            "kl_divergence" : kl_score,
            "mse"           : mse_score,
            "acc_fp32"      : acc_fp32,
            "acc_quantized" : acc_quant,
            "acc_drop"      : acc_drop,
            "time_sec"      : round(layer_sec, 2)
        }
        save_results(results)

        # ETA based on average time per layer so far
        layers_run  += 1
        elapsed      = time.time() - scan_start
        avg_per_layer= elapsed / layers_run
        eta_sec      = avg_per_layer * (len(remaining) - layers_run)

        verdict = "SENSITIVE" if kl_score > KL_THRESHOLD else "RESILIENT"
        suffix  = f"  (ETA: {format_eta(eta_sec)})"
        print_row(i, layer_name, kl_score, mse_score, verdict, suffix)

    # ── Final Summary ─────────────────────────────────────────────────────────
    total_min = (time.time() - scan_start) / 60
    print("\n  " + "─" * 76)
    print(f"  SCAN COMPLETE — {len(layer_names)} layers | {total_min:.1f} minutes total")
    print("  " + "─" * 76)

    # Rank all layers by KL divergence
    ranked = sorted(results.items(),
                    key=lambda x: x[1]['kl_divergence'],
                    reverse=True)

    sensitive_count = sum(1 for _, r in ranked if r['kl_divergence'] > KL_THRESHOLD)
    resilient_count = len(ranked) - sensitive_count

    print(f"\n  Sensitive layers (KL > {KL_THRESHOLD:.0e}) : {sensitive_count}")
    print(f"  Resilient layers                    : {resilient_count}")

    print("\n  ── Top 5 Most SENSITIVE (highest KL — keep at FP32) ──────────────")
    for name, r in ranked[:5]:
        print(f"     KL: {r['kl_divergence']:.6f}  |  {name}")

    print("\n  ── Top 5 Most RESILIENT (lowest KL — safe to quantize) ───────────")
    for name, r in ranked[-5:]:
        print(f"     KL: {r['kl_divergence']:.6f}  |  {name}")

    # ── Write human-readable summary file ─────────────────────────────────────
    with open("sensitivity_summary.txt", "w") as f:
        f.write("DistilBERT SST-2 — Layer Sensitivity Scan Results\n")
        f.write(f"Eval samples : {EVAL_SAMPLES}\n")
        f.write(f"Baseline acc : {acc_fp32 * 100:.2f}%\n")
        f.write(f"KL threshold : {KL_THRESHOLD}\n\n")
        f.write(f"{'Rank':<6}{'Layer Name':<62}{'KL Score':<14}{'MSE':<14}Verdict\n")
        f.write("─" * 110 + "\n")
        for rank, (name, r) in enumerate(ranked, 1):
            verdict = "SENSITIVE" if r['kl_divergence'] > KL_THRESHOLD else "RESILIENT"
            f.write(f"{rank:<6}{name:<62}{r['kl_divergence']:<14.6f}{r['mse']:<14.6f}{verdict}\n")

    print(f"\n  Results JSON    → {RESULTS_FILE}")
    print(f"  Readable summary → sensitivity_summary.txt")
    print(f"\n  Run step4_plot_map.py next to generate your sensitivity chart.\n")


if __name__ == "__main__":
    main()
